// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("140.555")]
[assembly: AssemblyFileVersion("140.555")]
[assembly: AssemblyInformationalVersion("140.555+71e44fc")]
